version: "3.7"
services:

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
        
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config"
    ports:
      - 9696:9696
    restart: unless-stopped
    
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - "${CONFIG_DIR}/sonarr:/config"
      - "${TV_DIR}:/tv"
      - "${DOWNLOADS_DIR}:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
   
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${MOVIES_DIR}:/movies"
      - "${DOWNLOADS_DIR}:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped

#   nzbget:
#     image: linuxserver/nzbget
#     container_name: nzbget
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=America/Detroit
#     # network_mode: service:openvpn-client
#     volumes:
#       - "${CONFIG_DIR}/nzbget:/config"
#       - "${DOWNLOADS_DIR}:/downloads"
#       - /docker/intermediate:/intermediate
#     ports:
#       - 5678:6789
#     restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
    volumes:
      - "${CONFIG_DIR}/sabnzbd/config:/config"
      - "${DOWNLOADS_DIR}:/downloads" #optional
      - /docker/intermediate:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Detroit
    ports:
      - 5055:5055
    volumes:
      - "${CONFIG_DIR}/overseerr/config:/app/config"
    restart: unless-stopped
    
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    volumes:
      - "${CONFIG_DIR}/tautulli:/config"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
    ports:
      - 8181:8181
    restart: unless-stopped

  influxarr:
    image: influxdb:2.7.4
    container_name: influxdb2
    ports:
      - 8086:8086
    volumes:
      - "${LOCAL_DIR}/influxdb2:/var/lib/influxdb2"
    restart: unless-stopped
