version: "3.7"
services:

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - "${CONFIG_DIR}/homarr/configs:/app/data/configs"
      - "${CONFIG_DIR}/homarr/icons:/app/public/icons"
    ports:
      - '7575:7575'

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
    volumes:
      - "${CONFIG_DIR}/prowlarr:/config"
    ports:
      - 9696:9696
    restart: unless-stopped
    
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - "${CONFIG_DIR}/sonarr:/config"
      - "${TV_DIR}:/tv"
      - "${DOWNLOADS_DIR}:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
   
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${MOVIES_DIR}:/movies"
      - "${DOWNLOADS_DIR}:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
    # network_mode: service:openvpn-client
    volumes:
      - "${CONFIG_DIR}/nzbget:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - /docker/intermediate:/intermediate
    ports:
      - 6789:6789
    restart: unless-stopped
    
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Detroit
    ports:
      - 5055:5055
    volumes:
      - "${CONFIG_DIR}/overseerr/config:/app/config"
    restart: unless-stopped
