version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /dev/rtc:/dev/rtc:ro
      - "${CONFIG_DIR}/sonarr:/config"
      - "${TV_DIR}:/tv"
      - "${DOWNLOADS_DIR}:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
      - UMASK_SET=022 #optional
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${MOVIES_DIR}:/movies"
      - "${DOWNLOADS_DIR}:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Detroit
    # network_mode: service:openvpn-client
    volumes:
      - "${CONFIG_DIR}/nzbget:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - /docker/intermediate:/intermediate
    ports:
      - 6789:6789
    restart: unless-stopped
