version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - "${CONFIG_DIR}/prometheus:/etc/prometheus"
   
