version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
        
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - "${LOCAL_DIR}/prometheus:/etc/prometheus"
      - "${LOCAL_DIR}/prometheus/data:/prometheus"
    restart: unless-stopped

  wyze-bridge:
    container_name: wyze-bridge
    image: mrlt8/wyze-bridge:nightly
    restart: unless-stopped
    environment:
      - QUALITY_BACKYARD_CAM=SD60
      - QUALITY_SIDEWAY_CAM=SD60
      - QUALITY_DRIVEWAY_CAM=SD60
      - QUALITY=HD180
      - "MQTT_HOST=${MQTT_HOST}"
      - "MQTT_AUTH=${MQTT_AUTH}"
      - MQTT_DTOPIC=homeassistant
    ports:
        - 8554:8554
        - 8888:8888
        - 5000:5000

  dashboard:
    image: phntxx/dashboard:latest
    restart: unless-stopped
    volumes:
      - "${LOCAL_DIR}:/app/data"
    ports:
      - 8080:8080
