version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        
  emqx:
    image: 'emqx/emqx:5.0.9'
    container_name: emqx
    ports:
      - '1883:1883'
      - '8083:8083'
      - '8084:8084'
      - '8883:8883'
      - '18083:18083'
        
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - "${LOCAL_DIR}/prometheus:/etc/prometheus"
      
