version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        
  eclipse-mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - "${LOCAL_DIR}/mosquitto:/mosquitto"
      
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - "${LOCAL_DIR}/prometheus:/etc/prometheus"
      
