version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
        
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - "${LOCAL_DIR}/prometheus:/etc/prometheus"
      - "${LOCAL_DIR}/prometheus/data:/prometheus"
    restart: unless-stopped

  wyze-bridge:
    container_name: wyze-bridge
    image: mrlt8/wyze-bridge:nightly
    restart: unless-stopped
    ports:
        - 8554:8554
        - 8888:8888
        - 5000:5000
      
      
#   omada-controller:
#     container_name: omada-controller
#     image: mbentley/omada-controller:5.13
#     restart: unless-stopped
#     ulimits:
#       nofile:
#         soft: 4096
#         hard: 8192
#     stop_grace_period: 60s
#     network_mode: host
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - MANAGE_HTTP_PORT=8088
#       - MANAGE_HTTPS_PORT=8043
#       - PORTAL_HTTP_PORT=8088
#       - PORTAL_HTTPS_PORT=8843
#       - PORT_APP_DISCOVERY=27001
#       - PORT_ADOPT_V1=29812
#       - PORT_UPGRADE_V1=29813
#       - PORT_MANAGER_V1=29811
#       - PORT_MANAGER_V2=29814
#       - PORT_DISCOVERY=29810
#       - PORT_TRANSFER_V2=29815
#       - PORT_RTTY=29816
#       - SHOW_SERVER_LOGS=true
#       - SHOW_MONGODB_LOGS=false
#       - SSL_CERT_NAME=tls.crt
#       - SSL_KEY_NAME=tls.key
#       - TZ=America/Detroit
#     volumes:
#       - omada-data:/opt/tplink/EAPController/data
#       - omada-logs:/opt/tplink/EAPController/logs
# volumes:
#   omada-data:
#   omada-logs:
